name: CUNSB
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8  
  - numpy=1.24.4
  - pandas=2.0.3
  - scipy=1.10.1
  - opencv=4.10.0
  - pillow=11.0.0
  - tqdm=4.66.4
  - torchvision=0.10.0
  - pip  
  - pip:
      - apex==0.9.10dev
      - beautifulsoup4==4.12.3
      - blobfile==3.0.0
      - dominate==2.9.1
      - einops==0.8.0
      - omegaconf==2.3.0
      - opencv_python_headless==4.10.0.84
      - packaging==24.1
      - prdc==0.2
      - pytorch_msssim==1.0.0
      - requests==2.32.3
      - skimage==0.0
      - torch==1.9.0+cu111
      - torchmetrics==1.4.0.post0
      - visdom==0.2.4
